//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Genesis_Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Item
    {
        public int InvItem_ID { get; set; }
        public int Part_ID { get; set; }
        public int Inv_ID { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        // public virtual Part Part { get; set; }
    }
}
