//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Genesis_Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Invoice_Item = new HashSet<Invoice_Item>();
        }
    
        public int Inv_ID { get; set; }
        public int InvItem_ID { get; set; }
        public int Cus_ID { get; set; }
        public int Vehicle_ID { get; set; }
        public decimal Inv_LabourTime { get; set; }
        public decimal Inv_LabourRate { get; set; }
        public decimal Inv_TaxRate { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Item> Invoice_Item { get; set; }
        public virtual Invoice_Item Invoice_Item1 { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
