//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Genesis_Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_Part
    {
        public int VehiclePart_ID { get; set; }
        public int Vehicle_ID { get; set; }
        public int Part_ID { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
